import { useState } from "react";
import { shuffle } from "lodash";
import Head from "next/head";
import Teams from "../components/Teams";
import { createTeams } from "../utils/createTeams";
import styles from "../styles/Home.module.css";
import { Button } from "reactstrap";

const Home = ({ players }) => {
  const [shufflePlayers, setShufflePlayers] = useState(createTeams(players));
  const [showTeams, setShowTeams] = useState(false);

  const sortTeams = () => {
    setTimeout(() => {
      setShufflePlayers(createTeams(shuffle(players)));
    }, 700);
    setShowTeams(true);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Generador de equipos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Teams players={shufflePlayers} showTeams={showTeams} />
        <Button
          color="danger"
          className={styles.button}
          onClick={() => sortTeams()}
        >
          Sortear Equipos
        </Button>
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/players");
  const players = await res.json();

  return {
    props: { players },
  };
}

export default Home;
