import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import PlayerList from "../components/PlayerList";
import Teams from "../components/Teams";
import styles from "../styles/Home.module.css";

const Home = ({ players }) => {
  const [teams, setTeams] = useState();
  console.log("🚀 ~ file: index.js ~ line 10 ~ Home ~ teams", teams);

  const sortTeams = () => {
    const random = players
      .map((player) => ({ player, sort: Math.random() }))
      .sort((a, b) => a.sort - b.sort)
      .reduce(
        (acc, { player }, i) => {
          if (i < players.length / 2) {
            acc.team1.push(player);
          } else {
            acc.team2.push(player);
          }
          return acc;
        },
        { team1: [], team2: [] }
      );

    setTeams(random);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Generador de equipos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PlayerList players={players} />
        <button onClick={() => sortTeams()}>Sort Teams</button>

        {teams !== undefined && <Teams teams={teams} />}
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/players");
  const players = await res.json();

  return {
    props: { players },
  };
}

export default Home;
